on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GOD_MODE }}
          release-type: dart

  publish_windows:
    runs-on: windows-latest
    needs: release_please
    if: ${{ needs.release_please.outputs.release_created }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - name: Zip Windows build
        run: |
          cd build\windows\x64\runner\Release
          Compress-Archive -Path . -Destination salus_gym_windows_x64.zip
      - name: Add Artifact to Release
        if: ${{ needs.release_please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GOD_MODE }}
        run: gh release upload ${{ needs.release_please.outputs.tag_name }} ./build/windows/x64/runner/Release/salus_gym_windows_x64.zip

  publish_linux_x64:
    runs-on: ubuntu-latest
    needs: release_please
    steps:
      - name: Install GTK3
        run: |
          sudo apt update -y
          sudo apt install -y libgtk-3-dev
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build linux --target-platform linux-x64
      - name: Zip Linux build
        run: |
          cd build/linux/x64/release/bundle
          zip -r salus_gym_linux_x64.zip *
      - name: Add Artifact to Release
        if: ${{ needs.release_please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GOD_MODE }}
        run: gh release upload ${{ needs.release_please.outputs.tag_name }} ./build/linux/x64/release/bundle/salus_gym_linux_x64.zip
